FROM testcon:0.0
ADD ./build/libs/ReactiveRESTfulWebService-0.0.1-SNAPSHOT.jar /ReactiveRESTfulWebService-0.0.1-SNAPSHOT.jar
EXPOSE 18080
CMD java -jar /home/ReactiveRESTfulWebService-0.0.1-SNAPSHOT.jar
