FROM testcon
ADD /var/lib/jenkins/workspace/Freestyle/ReactiveRESTfulWebService/build/libs/ReactiveRESTfulWebService-0.0.1-SNAPSHOT.jar /home
EXPOSE 18080
CMD java -jar /home/ReactiveRESTfulWebService-0.0.1-SNAPSHOT.jar