FROM testcon:0.0
ADD ReactiveRESTfulWebService/build/libs/ReactiveRESTfulWebService-0.0.1-SNAPSHOT.jar /ReactiveRESTfulWebService-0.0.1-SNAPSHOT.jar
EXPOSE 18080
CMD java -jar /ReactiveRESTfulWebService-0.0.1-SNAPSHOT.jar

